name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-2022
    timeout-minutes: 3600

    steps:
      - name: Configure Core RDP Settings
        run: |
          # Enable Remote Desktop and disable Network Level Authentication (if needed)
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
                             -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "SecurityLayer" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "PortNumber" -Value ${{ secrets.RDP_PORT }} -Force

          # Remove any existing rule with the same name to avoid duplication
          netsh advfirewall firewall delete rule name="RDP-Tailscale"
          
          # Allow incoming connection on the specified RDP port
          netsh advfirewall firewall add rule name="RDP-Tailscale" `
            dir=in action=allow protocol=TCP localport=${{ secrets.RDP_PORT }}

          # Restart the Remote Desktop service to ensure changes take effect
          Restart-Service -Name TermService -Force

      - name: Configure RDP User
        run: |
          $username = "${{ secrets.RDP_USERNAME }}"
          $password = "${{ secrets.RDP_PASSWORD }}"
          
          # Check if user exists, if not, create it
          if (-not (Get-LocalUser -Name $username -ErrorAction SilentlyContinue)) {
              $securePass = ConvertTo-SecureString $password -AsPlainText -Force
              New-LocalUser -Name $username -Password $securePass -AccountNeverExpires
          } else {
              # Update password if user exists
              $securePass = ConvertTo-SecureString $password -AsPlainText -Force
              Set-LocalUser -Name $username -Password $securePass
          }
          
          # Ensure user is in required groups
          Add-LocalGroupMember -Group "Administrators" -Member $username -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username -ErrorAction SilentlyContinue
          
          if (-not (Get-LocalUser -Name $username)) {
              Write-Error "User configuration failed"
              exit 1
          }

      - name: Install Tailscale
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
          
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
          Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
          Remove-Item $installerPath -Force

      - name: Establish Tailscale Connection
        run: |
          # Bring up Tailscale with the provided auth key and set a unique hostname
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$env:GITHUB_RUN_ID
          
          # Wait for Tailscale to assign an IP
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 10) {
              $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
              Start-Sleep -Seconds 5
              $retries++
          }
          
          if (-not $tsIP) {
              Write-Error "Tailscale IP not assigned. Exiting."
              exit 1
          }
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV
      
      - name: Verify RDP Accessibility
        run: |
          Write-Host "Tailscale IP: $env:TAILSCALE_IP"
          
          # Test connectivity using Test-NetConnection against the Tailscale IP on the specified RDP port
          $testResult = Test-NetConnection -ComputerName $env:TAILSCALE_IP -Port ${{ secrets.RDP_PORT }}
          if (-not $testResult.TcpTestSucceeded) {
              Write-Error "TCP connection to RDP port ${{ secrets.RDP_PORT }} failed"
              exit 1
          }
          Write-Host "TCP connectivity successful!"

      - name: Save RDP Credentials to Artifact
        run: |
          echo "Address: $env:TAILSCALE_IP" > rdp-credentials.txt
          echo "Username: ${{ secrets.RDP_USERNAME }}" >> rdp-credentials.txt
          echo "Password: ${{ secrets.RDP_PASSWORD }}" >> rdp-credentials.txt
          echo "Port: ${{ secrets.RDP_PORT }}" >> rdp-credentials.txt

      - name: Upload RDP Credentials as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rdp-credentials
          path: rdp-credentials.txt

      - name: Maintain Connection
        run: |
          Write-Host "`n=== RDP ACCESS ==="
          Write-Host "Address: $env:TAILSCALE_IP"
          Write-Host "Port: ${{ secrets.RDP_PORT }}"
          Write-Host "Credentials: Download 'rdp-credentials' artifact from the workflow run"
          Write-Host "==================`n"
          
          # Keep runner active indefinitely (or until manually cancelled)
          while ($true) {
              Write-Host "[$(Get-Date)] RDP Active - Use Ctrl+C in workflow to terminate"
              Start-Sleep -Seconds 300
          }
