name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-2022
    timeout-minutes: 360  # Reduced to 6 hours max for GitHub limits

    steps:
      - name: Download Pre-Required Files
        run: |
          # Create a downloads directory
          New-Item -ItemType Directory -Force -Path "$env:TEMP\Downloads"
          
          # Download unMiner example (add more URLs as needed)
          $unMinerUrl = "https://cdn.unmineable.download/unMiner.2.8.0-beta.exe"
          $unMinerPath = "$env:TEMP\Downloads\unMiner.exe"
          try {
              Invoke-WebRequest -Uri $unMinerUrl -OutFile $unMinerPath -ErrorAction Stop
              Write-Host "Downloaded unMiner to $unMinerPath"
          } catch {
              Write-Error ("Failed to download unMiner: {0}" -f $_.Exception.Message)
              exit 1
          }
          
          Write-Host "Pre-required files downloaded to $env:TEMP\Downloads"

      - name: Configure Core RDP Settings
        run: |
          # Enable Remote Desktop and disable NLA as requested
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
                             -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "SecurityLayer" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "PortNumber" -Value ${{ secrets.RDP_PORT }} -Force

          # Remove any existing rule with the same name to avoid duplication
          netsh advfirewall firewall delete rule name="RDP-Tailscale" 2>$null
          
          # Allow incoming connection on the specified RDP port
          netsh advfirewall firewall add rule name="RDP-Tailscale" `
            dir=in action=allow protocol=TCP localport=${{ secrets.RDP_PORT }}

          # Restart the Remote Desktop service to ensure changes take effect
          try {
              Restart-Service -Name TermService -Force -ErrorAction Stop
              Write-Host "Remote Desktop service restarted successfully"
          } catch {
              Write-Error ("Failed to restart TermService: {0}" -f $_.Exception.Message)
              exit 1
          }

      - name: Configure RDP User (runneradmin)
        run: |
          $username = "runneradmin"
          $password = "${{ secrets.RDP_PASSWORD }}"
          
          # Validate password
          if ([string]::IsNullOrWhiteSpace($password)) {
              Write-Error "Password is empty or invalid"
              exit 1
          }
          
          Write-Host "Configuring user: $username"
          
          # Check if runneradmin exists
          if (-not (Get-LocalUser -Name $username -ErrorAction SilentlyContinue)) {
              Write-Error "User runneradmin does not exist on this runner"
              exit 1
          }
          
          # Update password for runneradmin
          try {
              $securePass = ConvertTo-SecureString $password -AsPlainText -Force
              Set-LocalUser -Name $username -Password $securePass -ErrorAction Stop
              Write-Host "Password updated for user $username"
          } catch {
              Write-Error ("Failed to update password for {0}: {1}" -f $username, $_.Exception.Message)
              exit 1
          }
          
          # Ensure user is in Remote Desktop Users group
          try {
              Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username -ErrorAction Stop
              Write-Host "User $username added to Remote Desktop Users group"
          } catch {
              Write-Error ("Failed to add {0} to Remote Desktop Users: {1}" -f $username, $_.Exception.Message)
              exit 1
          }
          
          # Force group policy update to apply changes
          try {
              gpupdate /force
              Write-Host "Group policy updated successfully"
          } catch {
              Write-Warning ("Failed to update group policy: {0}" -f $_.Exception.Message)
          }
          
          # Verify user exists and is enabled
          $user = Get-LocalUser -Name $username -ErrorAction SilentlyContinue
          if (-not $user -or -not $user.Enabled) {
              Write-Error "User $username does not exist or is disabled"
              exit 1
          }
          
          # Debug: List user details
          Write-Host "User Details:"
          Write-Host "Name: $username"
          Write-Host "Enabled: $($user.Enabled)"
          Write-Host "SID: $($user.SID)"
          Write-Host "Member of Remote Desktop Users: $((Get-LocalGroupMember -Group 'Remote Desktop Users' | Where-Object { $_.Name -like "*$username" }) -ne $null)"

      - name: Install Tailscale
        run: |
          # Use latest stable version for security
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
          
          try {
              Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath -ErrorAction Stop
              Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
              Remove-Item $installerPath -Force
              Write-Host "Tailscale installed successfully"
          } catch {
              Write-Error ("Failed to install Tailscale: {0}" -f $_.Exception.Message)
              exit 1
          }

      - name: Establish Tailscale Connection
        run: |
          # Bring up Tailscale with the provided auth key and set a unique hostname
          try {
              & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$env:GITHUB_RUN_ID
              Write-Host "Tailscale connection initiated"
          } catch {
              Write-Error ("Failed to start Tailscale: {0}" -f $_.Exception.Message)
              exit 1
          }
          
          # Wait for Tailscale to assign an IP
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 15) {
              $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
              Start-Sleep -Seconds 5
              $retries++
          }
          
          if (-not $tsIP) {
              Write-Error "Tailscale IP not assigned. Exiting."
              exit 1
          }
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV
          Write-Host "Tailscale IP assigned: $tsIP"

      - name: Verify RDP Accessibility
        run: |
          Write-Host "Tailscale IP: $env:TAILSCALE_IP"
          
          # Test connectivity using Test-NetConnection against the Tailscale IP on the specified RDP port
          try {
              $testResult = Test-NetConnection -ComputerName $env:TAILSCALE_IP -Port ${{ secrets.RDP_PORT }} -ErrorAction Stop
              if (-not $testResult.TcpTestSucceeded) {
                  Write-Error "TCP connection to RDP port ${{ secrets.RDP_PORT }} failed"
                  exit 1
              }
              Write-Host "TCP connectivity successful!"
          } catch {
              Write-Error ("Failed to verify RDP connectivity: {0}" -f $_.Exception.Message)
              exit 1
          }

      - name: Display RDP Access Info (Only IP - No Credentials)
        run: |
          Write-Host "`n=== RDP ACCESS ==="
          Write-Host "Tailscale IP: $env:TAILSCALE_IP"
          Write-Host "Port: ${{ secrets.RDP_PORT }}"
          Write-Host "Use username 'runneradmin' and your pre-configured password to connect via RDP client."
          Write-Host "==================`n"

      - name: Periodic Backup Script (Runs in Background)
        run: |
          # PowerShell script to backup a specific folder every hour and send to Telegram bot
          # Assumptions: Folder to backup is C:\MyBackupFolder (change as needed)
          # Requires secrets: TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID
          
          $backupFolder = "C:\MyBackupFolder"  # Change to your target folder
          $botToken = "${{ secrets.TELEGRAM_BOT_TOKEN }}"
          $chatId = "${{ secrets.TELEGRAM_CHAT_ID }}"
          $maxFileSizeMB = 50  # Telegram limit ~50MB per file
          
          if (-not (Test-Path $backupFolder)) {
              Write-Host "Backup folder $backupFolder does not exist. Creating empty one."
              New-Item -ItemType Directory -Force -Path $backupFolder
          }
          
          # Function to create ZIP and send to Telegram
          function Send-BackupToTelegram {
              param($zipPath, $description)
              
              # Check file size
              $fileSizeMB = (Get-Item $zipPath).Length / 1MB
              if ($fileSizeMB -gt $maxFileSizeMB) {
                  Write-Host "Backup file too large ($([math]::Round($fileSizeMB, 2))MB). Skipping send."
                  return
              }
              
              # Send via Telegram API
              $uri = "https://api.telegram.org/bot$botToken/sendDocument"
              $boundary = [System.Guid]::NewGuid().ToString()
              $LF = "`r`n"
              
              $bodyLines = @(
                  "--$boundary",
                  "Content-Disposition: form-data; name=`"chat_id`"$LF",
                  $chatId,
                  "--$boundary",
                  "Content-Disposition: form-data; name=`"caption`"$LF",
                  $description,
                  "--$boundary",
                  "Content-Disposition: form-data; name=`"document`"; filename=`"$(Split-Path $zipPath -Leaf)`"$LF",
                  "Content-Type: application/zip$LF$LF",
                  [System.IO.File]::ReadAllBytes($zipPath),
                  "--$boundary--$LF"
              ) -join $LF
              
              try {
                  $response = Invoke-RestMethod -Uri $uri -Method Post -ContentType "multipart/form-data; boundary=$boundary" -Body ([Text.Encoding]::ASCII.GetBytes($bodyLines)) -ErrorAction Stop
                  if ($response.ok) {
                      Write-Host "Backup sent successfully: $description"
                      Remove-Item $zipPath -Force
                  } else {
                      Write-Error "Failed to send backup: $($response.description)"
                  }
              } catch {
                  Write-Error ("Failed to send backup to Telegram: {0}" -f $_.Exception.Message)
              }
          }
          
          # Background job to run every hour
          $jobScript = {
              param($backupFolder, $botToken, $chatId, $maxFileSizeMB)
              while ($true) {
                  $timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
                  $zipPath = "$env:TEMP\backup_$timestamp.zip"
                  
                  try {
                      Compress-Archive -Path "$backupFolder\*" -DestinationPath $zipPath -Force -ErrorAction Stop
                      $description = "Hourly backup from RDP runner - $timestamp (Size: $([math]::Round((Get-Item $zipPath).Length / 1MB, 2))MB)"
                      Send-BackupToTelegram -zipPath $zipPath -description $description
                  } catch {
                      Write-Error ("Failed to create or send backup: {0}" -f $_.Exception.Message)
                  }
                  Start-Sleep -Seconds 3600
              }
          }
          
          # Start the background job
          try {
              Start-Job -ScriptBlock $jobScript -ArgumentList $backupFolder, $botToken, $chatId, $maxFileSizeMB
              Write-Host "Backup job started: Will ZIP and send $backupFolder to Telegram every hour."
          } catch {
              Write-Error ("Failed to start backup job: {0}" -f $_.Exception.Message)
              exit 1
          }

      - name: Maintain Connection
        run: |
          Write-Host "`n=== RDP ACTIVE ==="
          Write-Host "Tailscale IP: $env:TAILSCALE_IP"
          Write-Host "Port: ${{ secrets.RDP_PORT }}"
          Write-Host "Backup job running in background."
          Write-Host "==================`n"
          
          # Keep runner active until cancelled
          while ($true) {
              Write-Host "[$(Get-Date)] RDP Active - Use Ctrl+C in workflow to terminate"
              Start-Sleep -Seconds 300
          }
